/**
 * Découpage SQL incrémental — source de vérité runtime par tranche.
 * Le monolithe 20260826_*.sql reste une vue d’ensemble ; exécuter les slices.
 */

export type SqlSliceStatus = 'ready' | 'later' | 'done'

export type SqlSliceMeta = {
  id: string
  file: string
  title: string
  status: SqlSliceStatus
  runNow: boolean
  summary: string
}

export const SQL_SLICES: SqlSliceMeta[] = [
  {
    id: '01_helpers_profiles',
    file: 'supabase/migrations/slices/01_helpers_profiles.sql',
    title: '01 — Helpers + profiles',
    status: 'done',
    runNow: false,
    summary: 'pgcrypto, profiles, trigger signup, helpers RLS, login_logs',
  },
  {
    id: '02_coach_tenancy',
    file: 'supabase/migrations/slices/02_coach_tenancy.sql',
    title: '02 — Tenancy coach',
    status: 'done',
    runNow: false,
    summary: 'coach_subscriptions (trial 15j) + coach_branding (slug)',
  },
  {
    id: '03_clients',
    file: 'supabase/migrations/slices/03_clients.sql',
    title: '03 — Clients CRM',
    status: 'done',
    runNow: false,
    summary: 'clients, groups, onboarding — appliqué + UI liste/fiche',
  },
  {
    id: '03b_fix_groups_rls',
    file: 'supabase/migrations/slices/03b_fix_groups_rls.sql',
    title: '03b — Fix RLS groupes',
    status: 'done',
    runNow: false,
    summary: 'Corrige recursion client_groups ↔ client_group_members',
  },
  {
    id: '04_prestations_grants',
    file: 'supabase/migrations/slices/04_prestations_grants.sql',
    title: '04 — Prestations + grants',
    status: 'done',
    runNow: false,
    summary: 'prestations, payment_ledger, client_grants — UI /payments + grants fiche client',
  },
  {
    id: '05_invites_showroom',
    file: 'supabase/migrations/slices/05_invites_showroom.sql',
    title: '05 — Invites + showroom',
    status: 'done',
    runNow: false,
    summary: 'client_invites + redeem · /c/[slug] · bouton inviter fiche client',
  },
  {
    id: '06_portal_rls',
    file: 'supabase/migrations/slices/06_portal_rls.sql',
    title: '06 — RLS portail',
    status: 'done',
    runNow: false,
    summary: 'Client lit prestations via grants',
  },
  {
    id: '07_redeem_guard',
    file: 'supabase/migrations/slices/07_redeem_guard.sql',
    title: '07 — Garde invite',
    status: 'done',
    runNow: false,
    summary: 'Coach ne peut pas redeem sa propre invite',
  },
  {
    id: '08_claim_client_email',
    file: 'supabase/migrations/slices/08_claim_client_email.sql',
    title: '08 — Claim par email',
    status: 'done',
    runNow: false,
    summary: 'Lie auth ↔ fiche client si email CRM = email auth',
  },
  {
    id: '09_client_user_unique',
    file: 'supabase/migrations/slices/09_client_user_unique.sql',
    title: '09 — Unique user_id',
    status: 'done',
    runNow: false,
    summary: '1 user_id par coach + délie doublons erronés',
  },
  {
    id: '10_programs',
    file: 'supabase/migrations/slices/10_programs.sql',
    title: '10 — Programmes',
    status: 'done',
    runNow: false,
    summary: 'programs + éditeur V2 + client_fitness_plans + FK presta',
  },
  {
    id: '11a_exercise_library_trainly',
    file: 'supabase/migrations/slices/11a_exercise_library_trainly.sql',
    title: '11a — Catalogue Trainly exercices',
    status: 'done',
    runNow: false,
    summary: 'Import 81 exercices coach_id NULL + chemins médias plats',
  },
  {
    id: '11a_exercise_media_storage',
    file: 'supabase/migrations/slices/11a_exercise_media_storage.sql',
    title: '11a — Bucket exercise-media',
    status: 'done',
    runNow: false,
    summary: 'Policies storage lecture auth + admin/coach write',
  },
  {
    id: '11_session_runs',
    file: 'supabase/migrations/slices/11_session_runs.sql',
    title: '11 — session_runs (player)',
    status: 'done',
    runNow: false,
    summary: 'Runs séance : styles Accueil · snapshot/realized · RLS client/coach',
  },
  {
    id: '12_home_calendar',
    file: '',
    title: '12 — Accueil calendrier (UI)',
    status: 'done',
    runNow: false,
    summary: 'Card semaine + pastilles styles + bandeau séances + Book plans — pas de SQL',
  },
  {
    id: '13_player_series',
    file: '',
    title: '13 — Player séries (UI)',
    status: 'done',
    runNow: false,
    summary: 'Pop-up demandé/réalisé · timer repos · Démarrer exo/bloc · realized.sets',
  },
  {
    id: '14_historique_runs',
    file: '',
    title: '14 — Historique runs (UI)',
    status: 'done',
    runNow: false,
    summary: 'Liste enrichie + fiche /historique/seance/[runId] (réalisé item/séries)',
  },
  {
    id: '15_client_favorites',
    file: 'supabase/migrations/slices/15_client_favorites.sql',
    title: '15 — Favoris + historique land',
    status: 'done',
    runNow: false,
    summary: 'client_favorites · land 1 ligne/exo|bloc · fiche Historique/Records/À propos',
  },
  {
    id: '16_chat',
    file: 'supabase/migrations/slices/16_chat.sql',
    title: '16 — Chat 1:1',
    status: 'done',
    runNow: false,
    summary: 'chat_threads/messages/reads · inbox coach /chat · portail /messages',
  },
  {
    id: '16b_client_read_coach_profile',
    file: 'supabase/migrations/slices/16b_client_read_coach_profile.sql',
    title: '16b — Client lit profil coach',
    status: 'done',
    runNow: false,
    summary: 'RLS profiles : client voit full_name de son coach (label Messages)',
  },
  {
    id: '17_client_diy_sessions',
    file: 'supabase/migrations/slices/17_client_diy_sessions.sql',
    title: '17 — Séances libres DIY',
    status: 'done',
    runNow: false,
    summary: 'client_diy_sessions · créer/jouer libre · hub Mes séances',
  },
  {
    id: '18_calendar_rdv',
    file: 'supabase/migrations/slices/18_calendar_rdv.sql',
    title: '18 — Calendrier RDV',
    status: 'done',
    runNow: false,
    summary: 'client propose créneau · coach Accept/Refuse · semaine coach · Accueil',
  },
  {
    id: '19_nutrition',
    file: 'supabase/migrations/slices/19_nutrition.sql',
    title: '19 — Nutrition',
    status: 'done',
    runNow: false,
    summary: 'recipes · plans jsonb · client plans · day logs · Accueil Repas',
  },
  {
    id: '20_exercise_status',
    file: 'supabase/migrations/slices/20_exercise_status.sql',
    title: '20 — Exercices status',
    status: 'done',
    runNow: false,
    summary: 'exercise_library status draft|published · type · coach /exercises',
  },
  {
    id: '21_drive',
    file: 'supabase/migrations/slices/21_drive.sql',
    title: '21 — Drive',
    status: 'done',
    runNow: false,
    summary: 'folders · files · shares · bucket drive · coach + Accueil Docs',
  },
  {
    id: '22_bilans',
    file: 'supabase/migrations/slices/22_bilans.sql',
    title: '22 — Bilans',
    status: 'done',
    runNow: false,
    summary: 'templates · instances J+14 · récurrences config · notifs table · bucket bilans',
  },
  {
    id: '23_compta',
    file: 'supabase/migrations/slices/23_compta.sql',
    title: '23 — Comptabilités',
    status: 'done',
    runNow: false,
    summary: 'payment_links_24h · invoice_requests · invoices · UI ledger/suivi/factures',
  },
  {
    id: '23b_payment_period',
    file: 'supabase/migrations/slices/23b_payment_period.sql',
    title: '23b — Période paiement',
    status: 'done',
    runNow: false,
    summary: 'payment_ledger.period_ym · unique indexes anti double Payé',
  },
  {
    id: '24_presta_content_links',
    file: 'supabase/migrations/slices/24_presta_content_links.sql',
    title: '24 — Liaisons contenu presta',
    status: 'done',
    runNow: false,
    summary: 'nutrition FK · drive_folder_id · auto-envoi au Payé',
  },
  {
    id: '25_one_started_plan',
    file: 'supabase/migrations/slices/25_one_started_plan.sql',
    title: '25 — Un plan started max',
    status: 'done',
    runNow: false,
    summary: 'unique started only · pause ne bloque plus le démarrage',
  },
  {
    id: '26_onboarding_completed',
    file: 'supabase/migrations/slices/26_onboarding_completed.sql',
    title: '26 — Onboarding completed',
    status: 'done',
    runNow: false,
    summary: 'clients.onboarding_completed_at · questionnaire nouveau compte',
  },
  {
    id: '33_support_tickets',
    file: 'supabase/migrations/slices/33_support_tickets.sql',
    title: '33 — Support tickets SAV',
    status: 'done',
    runNow: false,
    summary: 'support_tickets · support_messages · RLS coach/admin',
  },
  {
    id: '34_admin_coaches_ops',
    file: 'supabase/migrations/slices/34_admin_coaches_ops.sql',
    title: '34 — Admin coaches ops',
    status: 'done',
    runNow: false,
    summary: 'suspend · notes · opened_by · read cursors · trainly_drive_library',
  },
  {
    id: '35_trainly_library_formation_sav',
    file: 'supabase/migrations/slices/35_trainly_library_formation_sav.sql',
    title: '35 — Drive flags · Formation · SAV PJ',
    status: 'pending',
    runNow: true,
    summary: 'allow_duplicate/download · formation · attachments · buckets Storage',
  },
]
