import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShellClient from "../components/AppShellClient";
import { ProgramEditorNavigationProvider } from "../components/ProgramEditorNavigationClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeBoot = `(function(){try{var u=localStorage.getItem('trainly-theme-user');var t=u?localStorage.getItem('trainly-theme:'+u):null;if(t!=='light'&&t!=='dark')t=localStorage.getItem('trainly-theme');document.documentElement.dataset.theme=(t==='light'?'light':'dark');}catch(e){document.documentElement.dataset.theme='dark';}})();`

  return (
    <html lang="fr" data-theme="dark" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeBoot }} />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProgramEditorNavigationProvider>
          <AppShellClient>{children}</AppShellClient>
        </ProgramEditorNavigationProvider>
      </body>
    </html>
  );
}
